name: Build eza for macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Clone eza repository
      run: |
        git clone https://github.com/eza-community/eza.git
        cd eza

    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env
        rustup install stable
        rustup default stable

    - name: Build eza
      working-directory: eza
      run: |
        cargo build --release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: eza-macos-binary
        path: eza/target/release/eza
