name: Build safe-rm for macOS

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Release Binary
    runs-on: macos-13

    steps:
      - name: Download Source Code
        run: |
          curl -L -o safe-rm.tar.gz https://launchpad.net/safe-rm/trunk/1.1.0/+download/safe-rm-1.1.0.tar.gz
          tar -xvzf safe-rm.tar.gz --strip-components=1
          ls -al

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup install stable
          rustup default stable

      - name: Build Binary
        run: |
          cargo build --release
          pwd && ls -la
          

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: safe-rm-macos
          path: target/release/safe-rm
